_schema: _schema
source: /site/
paths:
  uploads: static/uploads
  static: static
collections_config:
  pages:
    path: content
    name: Pages
    icon: wysiwyg
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  post_brewing_chemex:
    path: content/post/brewing-chemex
    glob:
      - '!_index.md'
    name: Post Brewing Chemex
    icon: doorbell_chime
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  post_jamaica_blue:
    path: content/post/jamaica-blue
    glob:
      - '!_index.md'
    name: Post Jamaica Blue
    icon: event_available
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  post_making_sense:
    path: content/post/making-sense
    glob:
      - '!_index.md'
    name: Post Making Sense
    icon: breaking_news
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  data:
    path: data
    name: Data
    icon: data_usage
    disable_url: true
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
timezone: Europe/Amsterdam
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
